# Generated by Django 4.2.7 on 2025-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitted_function', models.TextField()),
                ('parameters', models.JSONField()),
                ('mse', models.FloatField(blank=True, null=True)),
                ('dominant_frequencies', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
