# Generated by Django 4.2.7 on 2025-06-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
