# Generated by Django 4.2.7 on 2025-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_signalanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalanalysis',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name for this analysis', max_length=100),
        ),
    ]
