# Generated by Django 4.2.7 on 2025-06-25 20:15

import django.core.validators
from django.db import migrations, models
import predictor.models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalanalysis',
            name='uploaded_file',
            field=models.FileField(upload_to=predictor.models.csv_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=predictor.models.user_profile_picture_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), predictor.models.validate_image_size]),
        ),
    ]
