# Generated by Django 4.2.7 on 2025-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalanalysis',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalanalysis',
            name='share_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
