# Generated by Django 4.2.7 on 2025-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='signalanalysis',
            name='data_preview',
            field=models.JSONField(blank=True, help_text='First 10 rows of the data', null=True),
        ),
        migrations.AddField(
            model_name='signalanalysis',
            name='fitted_signal_plot',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_plots/'),
        ),
        migrations.AddField(
            model_name='signalanalysis',
            name='frequency_analysis_plot',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_plots/'),
        ),
        migrations.AddField(
            model_name='signalanalysis',
            name='original_signal_plot',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_plots/'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
